import type { PrimitiveBindings } from "@mybrandos/integrations";
import { PrimitiveError } from "@mybrandos/integrations";
import { createHash } from "node:crypto";
import { prisma } from "../lib/prisma.js";
import { readJson } from "../lib/json.js";
import { createAsset, getAsset } from "./asset-service.js";
import { publishProductionSchedule } from "./offline-kernel-client.js";

export const MRFUNDZMAN_TV_CHANNEL = "mrfundzman.tv";
export const MRFUNDZMAN_TV_SCHEDULE = "mrfundzman.tv.daily";
type Source = "CREATOR_LIBRARY" | "DIRECT_UPLOAD" | "SUPPLIED" | "LICENSED" | "SYNDICATED" | "PUBLIC_DOMAIN" | "COMMISSIONED";
type Rights = "OWNED" | "LICENSED" | "SYNDICATED" | "SUPPLIED" | "COMMISSIONED" | "PUBLIC_DOMAIN" | "OTHER";
export type ProductionRights = { sourceType: Source; rightsBasis: Rights; rightsReference?: string | null; validFrom?: Date | null; validUntil?: Date | null; territory?: string | null; notes?: string | null; allowedChannels?: string[] };

function rightsData(rights: ProductionRights) {
  if (rights.validFrom && rights.validUntil && rights.validUntil < rights.validFrom) throw new Error("validUntil must not precede validFrom");
  return { ...rights, allowedChannels: JSON.stringify(rights.allowedChannels ?? ["TV"]) };
}
export async function listProductionItems(ownerId: string) { return prisma.productionLibraryItem.findMany({ where: { ownerId }, include: { asset: true }, orderBy: { updatedAt: "desc" } }); }
export async function getProductionItem(ownerId: string, id: string) { return prisma.productionLibraryItem.findFirst({ where: { id, ownerId }, include: { asset: true } }); }
export async function addCreatorAssetToProduction(ownerId: string, assetId: string, rights: ProductionRights) {
  if (!await getAsset(ownerId, assetId)) throw new Error("asset_not_found"); const data = rightsData(rights);
  return prisma.productionLibraryItem.upsert({ where: { ownerId_assetId: { ownerId, assetId } }, create: { ownerId, assetId, ...data }, update: data });
}
export async function createProductionItemForUploadedAsset(ownerId: string, file: { filename: string; mimeType: string; bytes: Buffer }, rights: ProductionRights, primitives: PrimitiveBindings) {
  let stored; try { stored = await primitives.dataZone.storeBytes(file); } catch (error) { if (error instanceof PrimitiveError) throw new Error(`datazone_${error.code}`); throw new Error("datazone_unavailable"); }
  if (!stored.dataZoneId) throw new Error("datazone_unavailable");
  const title = file.filename.replace(/\.[^.]+$/, "").replace(/[_-]+/g, " ").trim() || file.filename;
  const checksum = createHash("sha256").update(file.bytes).digest("hex");
  const asset = await createAsset({ ownerId, title, description: `Production upload: ${file.filename}`, assetType: "VIDEO", origin: "IMPORTED_FILE", originSource: file.filename, originRef: stored.dataZoneId, dataZoneId: stored.dataZoneId, visibility: "private", metadata: { filename: file.filename, mimeType: file.mimeType, sizeBytes: stored.sizeBytes, checksum, checksumAlgorithm: "sha256", productionUpload: true } });
  return { asset, item: await addCreatorAssetToProduction(ownerId, asset.id, { ...rights, sourceType: "DIRECT_UPLOAD" }) };
}
export async function updateProductionRights(ownerId: string, id: string, rights: ProductionRights) { if (!await getProductionItem(ownerId, id)) throw new Error("production_item_not_found"); return prisma.productionLibraryItem.update({ where: { id }, data: rightsData(rights) }); }
export async function removeProductionItem(ownerId: string, id: string) { if (!await getProductionItem(ownerId, id)) return false; await prisma.productionLibraryItem.delete({ where: { id } }); return true; }
export async function listPrograms(ownerId: string) { return prisma.broadcastProgram.findMany({ where: { ownerId, channelId: MRFUNDZMAN_TV_CHANNEL }, include: { productionItem: true }, orderBy: { createdAt: "desc" } }); }
export async function createProgram(ownerId: string, productionItemId: string, title: string) { const item = await getProductionItem(ownerId, productionItemId); if (!item) throw new Error("production_item_not_found"); const duration = Number(readJson<{ durationMs?: unknown }>(item.asset.metadata, {}).durationMs); return prisma.broadcastProgram.create({ data: { ownerId, channelId: MRFUNDZMAN_TV_CHANNEL, productionItemId, assetId: item.assetId, title, durationMs: Number.isFinite(duration) && duration > 0 ? duration : null } }); }
export async function createDraftSchedule(ownerId: string, startsAt: Date) { const current = await prisma.broadcastSchedule.aggregate({ where: { ownerId, scheduleId: MRFUNDZMAN_TV_SCHEDULE }, _max: { version: true } }); return prisma.broadcastSchedule.create({ data: { ownerId, channelId: MRFUNDZMAN_TV_CHANNEL, scheduleId: MRFUNDZMAN_TV_SCHEDULE, version: (current._max.version ?? 0) + 1, status: "DRAFT", startsAt } }); }
export async function getSchedule(ownerId: string, id: string) { return prisma.broadcastSchedule.findFirst({ where: { id, ownerId }, include: { entries: { include: { program: true }, orderBy: { sequence: "asc" } } } }); }
async function rebuildEntryTimes(scheduleId: string) { const schedule = await prisma.broadcastSchedule.findUnique({ where: { id: scheduleId }, include: { entries: { include: { program: true }, orderBy: { sequence: "asc" } } } }); if (!schedule) throw new Error("draft_schedule_not_found"); let cursor = schedule.startsAt; for (const [sequence, entry] of schedule.entries.entries()) { if (!entry.program.durationMs) throw new Error("duration_unknown"); const endsAt = new Date(cursor.getTime() + entry.program.durationMs); await prisma.broadcastScheduleEntry.update({ where: { id: entry.id }, data: { sequence, startsAt: cursor, endsAt } }); cursor = endsAt; } }
export async function addScheduleEntry(ownerId: string, scheduleId: string, programId: string) { const schedule = await getSchedule(ownerId, scheduleId); const program = await prisma.broadcastProgram.findFirst({ where: { id: programId, ownerId } }); if (!schedule || schedule.status !== "DRAFT" || !program) throw new Error("draft_schedule_or_program_not_found"); if (!program.durationMs) throw new Error("duration_unknown"); const last = schedule.entries.at(-1); const startsAt = last ? last.endsAt : schedule.startsAt; return prisma.broadcastScheduleEntry.create({ data: { scheduleId, programId, sequence: schedule.entries.length, startsAt, endsAt: new Date(startsAt.getTime() + program.durationMs) } }); }
export async function removeScheduleEntry(ownerId: string, scheduleId: string, entryId: string) { const schedule = await getSchedule(ownerId, scheduleId); if (!schedule || schedule.status !== "DRAFT" || !schedule.entries.some((entry) => entry.id === entryId)) throw new Error("draft_schedule_entry_not_found"); await prisma.broadcastScheduleEntry.delete({ where: { id: entryId } }); await rebuildEntryTimes(scheduleId); }
export async function reorderScheduleEntries(ownerId: string, scheduleId: string, entryIds: string[]) { const schedule = await getSchedule(ownerId, scheduleId); if (!schedule || schedule.status !== "DRAFT" || entryIds.length !== schedule.entries.length || new Set(entryIds).size !== entryIds.length || entryIds.some((id) => !schedule.entries.some((entry) => entry.id === id))) throw new Error("invalid_schedule_order"); for (const [sequence, id] of entryIds.entries()) await prisma.broadcastScheduleEntry.update({ where: { id }, data: { sequence: sequence + 1000 } }); for (const [sequence, id] of entryIds.entries()) await prisma.broadcastScheduleEntry.update({ where: { id }, data: { sequence } }); await rebuildEntryTimes(scheduleId); return getSchedule(ownerId, scheduleId); }
export async function setScheduleStart(ownerId: string, scheduleId: string, startsAt: Date) { const schedule = await getSchedule(ownerId, scheduleId); if (!schedule || schedule.status !== "DRAFT") throw new Error("draft_schedule_not_found"); await prisma.broadcastSchedule.update({ where: { id: scheduleId }, data: { startsAt } }); await rebuildEntryTimes(scheduleId); return getSchedule(ownerId, scheduleId); }
export function requiredMediaManifest(schedule: { entries: readonly { program: { assetId: string } }[] }) { return [...new Set(schedule.entries.map((entry) => entry.program.assetId))]; }
export async function publishSchedule(ownerId: string, id: string) { const schedule = await getSchedule(ownerId, id); if (!schedule || schedule.status !== "DRAFT") throw new Error("draft_schedule_not_found"); if (!schedule.entries.length) throw new Error("schedule_empty"); const published = await prisma.$transaction(async (tx) => { await tx.broadcastSchedule.updateMany({ where: { ownerId, channelId: schedule.channelId, status: "PUBLISHED" }, data: { status: "DRAFT" } }); return tx.broadcastSchedule.update({ where: { id }, data: { status: "PUBLISHED", publishedAt: new Date() }, include: { entries: { include: { program: true }, orderBy: { sequence: "asc" } } } }); }); const media = requiredMediaManifest(published); await prisma.broadcastSpaceSync.upsert({ where: { ownerId_channelId: { ownerId, channelId: published.channelId } }, create: { ownerId, channelId: published.channelId, spaceScheduleVersion: published.version, mediaReadyCount: 0, mediaRequiredCount: media.length }, update: { spaceScheduleVersion: published.version, mediaReadyCount: 0, mediaRequiredCount: media.length } }); await publishProductionSchedule({ ownerId, channelId: published.channelId, scheduleId: published.scheduleId, version: published.version, entries: published.entries.map((entry) => ({ assetId: entry.program.assetId, title: entry.program.title, durationMs: entry.program.durationMs!, startsAt: entry.startsAt, endsAt: entry.endsAt })) }); return published; }
