export {
  parseDigitalLifePath,
  assetDetailPath,
  assetsPath,
  favoritesPath,
  managementPath,
  communitiesPath,
  profilePath,
  specialtyChipsFor,
  assetsForSpecialtyChip,
  inferCreatorSpecialty,
  rankFavorites,
  joinPublicPath,
  publicHomePath,
  type DigitalLifeRoute,
  type DigitalLifeRoutePrimary,
  type SpecialtyChip,
  type CreatorSpecialty,
} from "@mybrandos/shared";
