CREATE TABLE "ProductionLibraryItem" ("id" TEXT NOT NULL PRIMARY KEY, "ownerId" TEXT NOT NULL, "assetId" TEXT NOT NULL, "sourceType" TEXT NOT NULL, "rightsBasis" TEXT NOT NULL, "rightsReference" TEXT, "validFrom" DATETIME, "validUntil" DATETIME, "territory" TEXT, "allowedChannels" TEXT NOT NULL DEFAULT '[]', "notes" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "ProductionLibraryItem_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset" ("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE UNIQUE INDEX "ProductionLibraryItem_ownerId_assetId_key" ON "ProductionLibraryItem"("ownerId","assetId");
CREATE TABLE "BroadcastProgram" ("id" TEXT NOT NULL PRIMARY KEY, "ownerId" TEXT NOT NULL, "channelId" TEXT NOT NULL, "productionItemId" TEXT NOT NULL, "assetId" TEXT NOT NULL, "title" TEXT NOT NULL, "durationMs" INTEGER, "status" TEXT NOT NULL DEFAULT 'DRAFT', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "BroadcastProgram_productionItemId_fkey" FOREIGN KEY ("productionItemId") REFERENCES "ProductionLibraryItem" ("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE "BroadcastSchedule" ("id" TEXT NOT NULL PRIMARY KEY, "ownerId" TEXT NOT NULL, "channelId" TEXT NOT NULL, "scheduleId" TEXT NOT NULL, "version" INTEGER NOT NULL, "status" TEXT NOT NULL, "startsAt" DATETIME NOT NULL, "publishedAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE UNIQUE INDEX "BroadcastSchedule_ownerId_scheduleId_version_key" ON "BroadcastSchedule"("ownerId","scheduleId","version");
CREATE TABLE "BroadcastScheduleEntry" ("id" TEXT NOT NULL PRIMARY KEY, "scheduleId" TEXT NOT NULL, "programId" TEXT NOT NULL, "sequence" INTEGER NOT NULL, "startsAt" DATETIME NOT NULL, "endsAt" DATETIME NOT NULL, CONSTRAINT "BroadcastScheduleEntry_scheduleId_fkey" FOREIGN KEY ("scheduleId") REFERENCES "BroadcastSchedule" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "BroadcastScheduleEntry_programId_fkey" FOREIGN KEY ("programId") REFERENCES "BroadcastProgram" ("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE UNIQUE INDEX "BroadcastScheduleEntry_scheduleId_sequence_key" ON "BroadcastScheduleEntry"("scheduleId","sequence");
CREATE TABLE "BroadcastSpaceSync" ("id" TEXT NOT NULL PRIMARY KEY, "ownerId" TEXT NOT NULL, "channelId" TEXT NOT NULL, "spaceScheduleVersion" INTEGER, "mediaReadyCount" INTEGER NOT NULL DEFAULT 0, "mediaRequiredCount" INTEGER NOT NULL DEFAULT 0, "updatedAt" DATETIME NOT NULL);
CREATE UNIQUE INDEX "BroadcastSpaceSync_ownerId_channelId_key" ON "BroadcastSpaceSync"("ownerId","channelId");
