import assert from "node:assert/strict";
import { after, before, test } from "node:test";
import { LocalDataZoneAdapter } from "@mybrandos/integrations";
import { prisma } from "../src/lib/prisma.js";
import { createAsset } from "../src/services/asset-service.js";
import { addCreatorAssetToProduction, addScheduleEntry, createDraftSchedule, createProductionItemForUploadedAsset, createProgram, getSchedule, publishSchedule, reorderScheduleEntries, requiredMediaManifest, updateProductionRights } from "../src/services/production-library-service.js";
const OWNER = "production-plane-owner"; const OTHER = "production-plane-other"; const rights = { sourceType: "CREATOR_LIBRARY" as const, rightsBasis: "OWNED" as const, allowedChannels: ["TV"] };
async function cleanup() { const schedules = await prisma.broadcastSchedule.findMany({ where: { ownerId: { in: [OWNER, OTHER] } }, select: { id: true } }); if (schedules.length) await prisma.broadcastScheduleEntry.deleteMany({ where: { scheduleId: { in: schedules.map((row) => row.id) } } }); await prisma.broadcastSchedule.deleteMany({ where: { ownerId: { in: [OWNER, OTHER] } } }); await prisma.broadcastProgram.deleteMany({ where: { ownerId: { in: [OWNER, OTHER] } } }); await prisma.broadcastSpaceSync.deleteMany({ where: { ownerId: { in: [OWNER, OTHER] } } }); await prisma.productionLibraryItem.deleteMany({ where: { ownerId: { in: [OWNER, OTHER] } } }); await prisma.activity.deleteMany({ where: { ownerId: { in: [OWNER, OTHER] } } }); await prisma.asset.deleteMany({ where: { ownerId: { in: [OWNER, OTHER] } } }); }
before(cleanup); after(async () => { await cleanup(); await prisma.$disconnect(); });
test("ten creator assets retain canonical asset ids through production and a versioned schedule", async () => { const items = []; for (let index = 0; index < 10; index += 1) { const asset = await createAsset({ ownerId: OWNER, title: `Episode ${index + 1}`, assetType: "VIDEO", origin: "CREATED_INTERNAL", metadata: { durationMs: 60_000 } }); const item = await addCreatorAssetToProduction(OWNER, asset.id, rights); assert.equal(item.assetId, asset.id); items.push(item); } const programs = await Promise.all(items.map((item, index) => createProgram(OWNER, item.id, `Program ${index + 1}`))); const schedule = await createDraftSchedule(OWNER, new Date("2026-09-25T10:00:00.000Z")); for (const program of programs) await addScheduleEntry(OWNER, schedule.id, program.id); const draft = await getSchedule(OWNER, schedule.id); assert.equal(draft?.entries.length, 10); assert.deepEqual(requiredMediaManifest(draft!), items.map((item) => item.assetId)); const published = await publishSchedule(OWNER, schedule.id); assert.equal(published.status, "PUBLISHED"); assert.equal(published.version, 1); const sync = await prisma.broadcastSpaceSync.findUnique({ where: { ownerId_channelId: { ownerId: OWNER, channelId: "mrfundzman.tv" } } }); assert.deepEqual({ version: sync?.spaceScheduleVersion, required: sync?.mediaRequiredCount }, { version: 1, required: 10 }); });
test("draft schedules recalculate ordered timing and reject unknown duration", async () => { const a = await createAsset({ ownerId: OTHER, title: "Known", assetType: "VIDEO", origin: "CREATED_INTERNAL", metadata: { durationMs: 120_000 } }); const b = await createAsset({ ownerId: OTHER, title: "Unknown", assetType: "VIDEO", origin: "CREATED_INTERNAL" }); const itemA = await addCreatorAssetToProduction(OTHER, a.id, rights); const itemB = await addCreatorAssetToProduction(OTHER, b.id, rights); const known = await createProgram(OTHER, itemA.id, "Known program"); const unknown = await createProgram(OTHER, itemB.id, "Unknown program"); const schedule = await createDraftSchedule(OTHER, new Date("2026-09-25T12:00:00.000Z")); const entry = await addScheduleEntry(OTHER, schedule.id, known.id); await assert.rejects(() => addScheduleEntry(OTHER, schedule.id, unknown.id), /duration_unknown/); const reordered = await reorderScheduleEntries(OTHER, schedule.id, [entry.id]); assert.equal(reordered?.entries[0]?.endsAt.toISOString(), "2026-09-25T12:02:00.000Z"); });
test("production upload persists once through DataZone, records SHA-256 bytes integrity, and owner-scopes rights changes", async () => { const uploaded = await createProductionItemForUploadedAsset(OWNER, { filename: "broadcast.mp4", mimeType: "video/mp4", bytes: Buffer.from("broadcast") }, { ...rights, sourceType: "DIRECT_UPLOAD" }, { dataZone: new LocalDataZoneAdapter() } as never); assert.equal(uploaded.item.assetId, uploaded.asset.id); assert.ok(uploaded.asset.dataZoneId); assert.equal(uploaded.asset.metadata.checksum, "e88199c423228a456677d367059b4f9b9fc769bae4a5c88aef9f7d0fcbe0726b"); assert.equal(uploaded.asset.metadata.checksumAlgorithm, "sha256"); const foreign = await createAsset({ ownerId: OTHER, title: "Foreign", assetType: "VIDEO", origin: "CREATED_INTERNAL" }); const foreignItem = await addCreatorAssetToProduction(OTHER, foreign.id, rights); await assert.rejects(() => updateProductionRights(OWNER, foreignItem.id, { ...rights, territory: "NG" }), /production_item_not_found/); });
